baseURL = "/"
languageCode = 'en-gb'
title = 'Aussie Legislation'
theme = 'hugo-whisper-theme'

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Constitution"
    url = "/constitution/"
    weight = 2

[params]
  homepage_button_link = '/constitution'
  homepage_button_text = 'See Constitution'
  homepage_intro = 'Proof of Concept'
  custom_css = ['css/diffs.css']

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"